### ISSUE TITLE
Does it have HTTP/2 support?

### ISSUE THREAD

**Issue by ConsoleTVs** [swhitty/FlyingFox#33]
First of all thanks for developing this amazing package!

I wanted to ask if it is possible to use http 2 with this package as I see the server is currently using HTTP/1.1.

**Comment by swhitty** [comment]
Thanks for the great feedback @ConsoleTVs.

HTTP/2 is not on the roadmap yet.  Mostly because of the [lack of TLS support](https://github.com/swhitty/FlyingFox/issues/34) and most clients negotiate HTTP/2 in the TLS handshake.

FlyingFox _could_ support upgrading to HTTP/2 Clear Text via `Upgrade: h2c` but I don't think there are many clients that utilise this upgrade. I don't believe [`URLSession`](https://developer.apple.com/documentation/foundation/urlsession) supports upgrading this way, if it did then we would probably add it to the roadmap.
